name: capsule_example
description: Demonstrates usage of Capsule Flutter SDK.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  capsule_flutter:
    path: ../flutter-sdk/
  flutter_inappwebview: ^5.8.0
  cupertino_icons: ^1.0.2
  uuid: ^4.1.0
  convert: ^3.1.1
  step_progress_indicator: ^1.0.2
  flutter_animate: ^4.2.0+1
  webauthn: ^0.2.3
  passkeys: ^2.0.2
  pointycastle: ^3.7.4
  pem: ^2.0.5
  basic_utils: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
